### ISSUE TITLE
Known Convictions and Owned Vehicles not displaying on profiles

### ISSUE THREAD

**Issue by Smorj** [Project-Sloth/qb-mdt#3]
The known convictions and owned vehicles tabs on a players profile does not display applied convictions or owned cars.

**Comment by Kolvicht** [comment]
> The known convictions and owned vehicles tabs on a players profile does not display applied convictions or owned cars.

https://i.imgur.com/d7aAAXL.png
This is working fine, just did a fresh install of both.

**Comment by MonkeyWhisper** [comment]
Thank you for confirming that. 

> > The known convictions and owned vehicles tabs on a players profile does not display applied convictions or owned cars.
> 
> https://i.imgur.com/d7aAAXL.png This is working fine, just did a fresh install of both.
