### ISSUE TITLE
Enhancement: Add the ability to remove charges

### ISSUE THREAD

**Issue by Fistsofury** [Project-Sloth/qb-mdt#5]
What: You cannot remove a charge, so if you accidently add a incorrect charge you need to adjust the sentencing or fines or create a new report and start it all again.

You can remove all other tags just not ones that relate to a charge.

**Comment by mastamadman** [comment]
If you go back into the report, go into the charges section and right click the charge you want to remove it should remove it.

**Comment by Fistsofury** [comment]
ahhhh i see thank you for that :). Suggestion still stands to have it appear on the main MDT board for consistency as thats what you can do for other tags. Its just and idea
