### ISSUE TITLE
Waypoint Not Setting

### ISSUE THREAD

**Issue by mastamadman** [Project-Sloth/qb-mdt#7]
When trying to set a waypoint to a recent call it errors out.

Attached are pictures of the error as well as the code snippet.

https://i.imgur.com/peA8Wve.png
https://i.imgur.com/aNQDHxV.png

**Comment by trclassic92** [comment]
It's not called un-dispatch anymore. You need to updated the mdt and dispatch system

**Comment by MonkeyWhisper** [comment]
This is already fixed. Make sure to update.
